
export const Think = [
  { key: 'overthinking', title: 'Thinking Too Much', emoji: '💭', tips: [ 'Write your thoughts down ✍️', 'Breathe slowly 💨', 'Take a break 🧘‍♂️' ] },
  { key: 'low-energy', title: 'Feeling Tired', emoji: '😴', tips: [ 'Drink water 💧', 'Take a walk 🚶', 'Stretch your body 🤸‍♀️' ] },
  { key: 'burnout', title: 'Too Much Work', emoji: '🔥', tips: [ 'Take a rest 🛌', 'Say “No” to more tasks 🙅‍♀️', 'Do something fun 🎨' ] },
  { key: 'panic', title: 'Feeling Scared', emoji: '😵', tips: [ 'Breathe slowly 💨', 'Talk to someone 📞', 'Ground yourself 👣' ] },
  { key: 'high-anxiety', title: 'Very Nervous', emoji: '😣', tips: [ 'Listen to calming music 🎧', 'Do 5-minute breathing ⏱️', 'Write in a journal 📓' ] },
  { key: 'empty', title: 'Feeling Nothing', emoji: '🌧️', tips: [ 'Do something small 🌱', 'Look outside 🌤️', 'Talk to someone 🧑‍🤝‍🧑' ] },
  { key: 'self-doubt', title: 'Not Feeling Good Enough', emoji: '🌀', tips: [ 'Write what you are good at 📝', 'Look in mirror and smile 🪞', 'Remember past wins 🏆' ] },
  { key: 'sad', title: 'Feeling Sad', emoji: '😢', tips: [ 'Watch something funny 😂', 'Cuddle a soft toy 🧸', 'Talk to a friend 🗣️' ] },
  { key: 'angry', title: 'Feeling Angry', emoji: '😡', tips: [ 'Take 3 deep breaths 💨', 'Go for a walk 🚶', 'Write what upset you 📝' ] },
  { key: 'lonely', title: 'Feeling Alone', emoji: '😔', tips: [ 'Text someone you miss 💬', 'Read a book 📖', 'Go outside 🌳' ] },
  { key: 'lost', title: 'Feeling Lost', emoji: '❓', tips: [ 'Write one small goal 🎯', 'Do one helpful thing 🤝', 'Say "It’s okay" to yourself 🤍' ] },
  { key: 'empty-social', title: 'Tired of People', emoji: '🙅‍♀️', tips: [ 'Take alone time 🧘‍♀️', 'Draw or write 🎨', 'Don’t feel guilty 🙌' ] },
  { key: 'jealousy', title: 'Feeling Jealous', emoji: '😒', tips: [ 'Think about your strengths 💚', 'Say: "I’m trying my best" 🌟', 'Take a break from social 📵' ] },
  { key: 'fear', title: 'Feeling Afraid', emoji: '😨', tips: [ 'Talk about it 🎤', 'Think of safe places 🏡', 'Do grounding steps 👣' ] },
  { key: 'stress', title: 'Too Much Stress', emoji: '😫', tips: [ 'Close eyes and breathe 🧘‍♂️', 'Take a 10-min break ⏸️', 'Drink something warm ☕' ] },
  { key: 'shame', title: 'Feeling Shame', emoji: '😞', tips: [ 'You’re still learning 📘', 'Everyone makes mistakes 🌱', 'Be kind to yourself 🤗' ] },
  { key: 'grief', title: 'Feeling Loss', emoji: '🖤', tips: [ 'Cry if you want 😢', 'Look at old photos 🖼️', 'Talk about them 💬' ] },
  { key: 'insecure', title: 'Not Confident', emoji: '😕', tips: [ 'Write 3 strengths 💪', 'Smile in the mirror 🪞', 'Dress well 👗' ] },
  { key: 'left-out', title: 'Feeling Left Out', emoji: '🚪', tips: [ 'Message a friend 💬', 'Join a group 🧑‍🏫', 'You matter ❤️' ] },
  { key: 'regret', title: 'Feeling Regret', emoji: '😔', tips: [ 'Say “I forgive myself” 🙏', 'Learn and move forward ⏩', 'Everyone makes mistakes ⚠️' ] },
  { key: 'rejected', title: 'Feeling Rejected', emoji: '🚫', tips: [ 'Rejection is redirection 🛣️', 'You’re still valuable 💎', 'Do something you enjoy 🎮' ] },
  { key: 'confused', title: 'Feeling Confused', emoji: '🤔', tips: [ 'Write pros and cons 📝', 'Talk it out 🗣️', 'Pause and reflect 🪞' ] },
  { key: 'social-anxiety', title: 'Nervous with People', emoji: '🙈', tips: [ 'Practice in mirror 🪞', 'Start with small talk 💬', 'Don’t judge yourself 🧠' ] },
  { key: 'irritated', title: 'Feeling Irritated', emoji: '😤', tips: [ 'Listen to calm music 🎵', 'Take deep breaths 💨', 'Do something calming 🧘' ] },
  { key: 'hurt', title: 'Feeling Hurt', emoji: '💢', tips: [ 'Write how you feel ✍️', 'Rest your mind 💤', 'Talk to a friend 🧑‍🤝‍🧑' ] },
  { key: 'hopeless', title: 'Feeling Hopeless', emoji: '🕳️', tips: [ 'This moment will pass 🌅', 'Think of someone who cares 🤝', 'Take one small step 🚶‍♀️' ] },
  { key: 'guilt', title: 'Feeling Guilty', emoji: '😓', tips: [ 'Say sorry if needed 🧎‍♀️', 'Don’t stay stuck there ⛅', 'Forgive yourself 🙏' ] },
  { key: 'comparison', title: 'Comparing Yourself', emoji: '📉', tips: [ 'Social media is not real life 📵', 'Focus on your path 🌈', 'You are unique 🌟' ] },
  { key: 'mind-block', title: 'Can’t Think Clearly', emoji: '🚫🧠', tips: [ 'Go for a walk 🚶', 'Change your space 🛋️', 'Do one small task ✅' ] },
];
